;;; poetry-virtualenv-test.el --- Tests for poetry.el


(ert-deftest poetry-virtualenv-should-be-activated-and-deactivated ()
  (cl-letf (((symbol-function 'pyvenv-activate)
             (lambda (dir)
               (setq pyvenv-virtual-env dir)))
            ((symbol-function 'directory-files)
             (lambda (dir &optional full match nosort)
               (list (format "%s%s" (file-name-as-directory dir)
                       (downcase (poetry-get-project-name)))))))
    (let* ((ppath (poetry-test-create-project-folder))
           (default-directory ppath))
      (poetry-add-dep "atomicwrites")
      ;; (poetry-add-dep "attrs")
      (poetry-venv-workon)
      (should (string-match "pypoetry/virtualenvs/poetry" pyvenv-virtual-env))
      (poetry-venv-deactivate)
      (should (not pyvenv-virtual-env))
      (poetry-venv-toggle)
      (should (string-match "pypoetry/virtualenvs/poetry" pyvenv-virtual-env))
      (poetry-venv-toggle)
      (should (not pyvenv-virtual-env)))))

(ert-deftest poetry-should-track-virtualenvs ()
  (cl-letf (((symbol-function 'pyvenv-activate)
             (lambda (dir)
               (setq pyvenv-virtual-env dir)))
            ((symbol-function 'directory-files)
             (lambda (dir &optional full match nosort)
               (list (format "%s%s" (file-name-as-directory dir)
                       (downcase (poetry-get-project-name)))))))
    (let* ((ppath (poetry-test-create-project-folder))
           (ppath2 (poetry-test-create-project-folder)))
      (let ((default-directory ppath))
        (poetry-add-dep "atomicwrites"))
      (let ((default-directory ppath2))
        (poetry-add-dep "attrs"))
      (poetry-tracking-mode 1)
      ;; project 1
      (find-file (concat (file-name-as-directory ppath)
                         "file1.py"))
      (run-hooks 'post-command-hook)
      (should (string-match "pypoetry/virtualenvs/poetry" pyvenv-virtual-env))
      ;; project 2
      (find-file (concat (file-name-as-directory ppath)
                         "file1.py"))
      (run-hooks 'post-command-hook)
      (should (string-match "pypoetry/virtualenvs/poetry" pyvenv-virtual-env))
      (poetry-tracking-mode -1)
      (poetry-venv-deactivate))))

;;; poetry-virtualenv-test.el ends here
